// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	repository2 "github.com/misyuari/go-omdb/domain/log/repository"
	use_case2 "github.com/misyuari/go-omdb/domain/log/use_case"
	"github.com/misyuari/go-omdb/domain/movie/delivery/rest"
	"github.com/misyuari/go-omdb/domain/movie/repository"
	"github.com/misyuari/go-omdb/domain/movie/use_case"
	"net/http"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from injector.go:

func InitializedHttpServer() *http.Server {
	movieRepository := repository.NewMovieRepository()
	movieUseCase := use_case.NewMovieUseCase(movieRepository)
	logRepository := repository2.NewLogRepository()
	logUseCase := use_case2.NewLogUseCase(logRepository)
	movieHandler := rest.NewMovieHandler(movieUseCase, logUseCase)
	router := rest.RegisterMovieRouter(movieHandler)
	server := NewServer(router)
	return server
}

// injector.go:

var movieSet = wire.NewSet(repository.NewMovieRepository, use_case.NewMovieUseCase, rest.NewMovieHandler, rest.RegisterMovieRouter, use_case2.NewLogUseCase, repository2.NewLogRepository)
