// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LogUseCase is an autogenerated mock type for the LogUseCase type
type LogUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: serverType, module, payload
func (_m *LogUseCase) Create(serverType string, module string, payload interface{}) {
	_m.Called(serverType, module, payload)
}
