// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	httprouter "github.com/julienschmidt/httprouter"
	mock "github.com/stretchr/testify/mock"
)

// MovieHandler is an autogenerated mock type for the MovieHandler type
type MovieHandler struct {
	mock.Mock
}

// Detail provides a mock function with given fields: writer, request, params
func (_m *MovieHandler) Detail(writer http.ResponseWriter, request *http.Request, params httprouter.Params) {
	_m.Called(writer, request, params)
}

// List provides a mock function with given fields: writer, request, params
func (_m *MovieHandler) List(writer http.ResponseWriter, request *http.Request, params httprouter.Params) {
	_m.Called(writer, request, params)
}
