// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	helper "github.com/misyuari/go-omdb/helper"
	mock "github.com/stretchr/testify/mock"

	model "github.com/misyuari/go-omdb/domain/movie/model"
)

// MovieUseCase is an autogenerated mock type for the MovieUseCase type
type MovieUseCase struct {
	mock.Mock
}

// Detail provides a mock function with given fields: id
func (_m *MovieUseCase) Detail(id string) *helper.Response {
	ret := _m.Called(id)

	var r0 *helper.Response
	if rf, ok := ret.Get(0).(func(string) *helper.Response); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helper.Response)
		}
	}

	return r0
}

// List provides a mock function with given fields: request
func (_m *MovieUseCase) List(request *model.MovieRequestList) *helper.Response {
	ret := _m.Called(request)

	var r0 *helper.Response
	if rf, ok := ret.Get(0).(func(*model.MovieRequestList) *helper.Response); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*helper.Response)
		}
	}

	return r0
}
